name: Financial Tests CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-api-tests:
    name: Build API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore financial-tests.sln

      - name: Build solution
        run: dotnet build financial-tests.sln --configuration Release --no-restore